### ISSUE TITLE
Parse and print webvital summary

### ISSUE THREAD

**Issue by ankur22** [grafana/xk6-browser#691]
This follows on from the POC https://github.com/grafana/xk6-browser/pull/657.

This requires a bit of investigation and you will need to work with other teams to work out how we want to display the event in the summary.
- How do we display the rating in the summary in a concise way?
- We should concentrate on the 75th percentile as suggested by Google: ["to ensure you're hitting the recommended target for most of your users, a good threshold to measure is the 75th percentile of page loads, segmented across mobile and desktop devices."](https://web.dev/vitals/#:~:text=to%20ensure%20you%27re%20hitting%20the%20recommended%20target%20for%20most%20of%20your%20users%2C%20a%20good%20threshold%20to%20measure%20is%20the%2075th%20percentile%20of%20page%20loads%2C%20segmented%20across%20mobile%20and%20desktop%20devices.%22)

**Comment by ankur22** [comment]
Curent summary output:

```
     webvital_cumulative_layout_shift....................: avg=0.002929 min=0.002727 med=0.002903 max=0.003211 p(90)=0.003211 p(95)=0.003211
     webvital_cumulative_layout_shift_good...............: 10     0.179492/s
     webvital_first_contentful_paint.....................: avg=1.09s    min=174.69ms med=1.05s    max=2.24s    p(90)=2.02s    p(95)=2.11s   
     webvital_first_contentful_paint_good................: 10     0.179492/s
     webvital_first_contentful_paint_needs_improvement...: 10     0.179492/s
     webvital_first_input_delay..........................: avg=48.54ms  min=32.8ms   med=47.75ms  max=58ms     p(90)=57.91ms  p(95)=57.95ms 
     webvital_first_input_delay_good.....................: 10     0.179492/s
     webvital_interaction_to_next_paint..................: avg=69.59ms  min=56ms     med=68ms     max=80ms     p(90)=80ms     p(95)=80ms    
     webvital_interaction_to_next_paint_good.............: 10     0.179492/s
     webvital_largest_content_paint......................: avg=399.53ms min=358.89ms med=406.04ms max=417.79ms p(90)=415.54ms p(95)=416.67ms
     webvital_largest_content_paint_good.................: 10     0.179492/s
     webvital_time_to_first_byte.........................: avg=221.98ms min=70.69ms  med=210.75ms max=484.9ms  p(90)=365.04ms p(95)=445.76ms
     webvital_time_to_first_byte_good....................: 20     0.358984/s
```

What might be better:

```
webvitals:
    cumulative_layout_shift....................: p(75)=0.003211 p(90)=0.003211 p(95)=0.003211
        rating.................................: good=10    needs_improvement=0    poor=0
    first_contentful_paint.....................: p(75)=2.02s    p(90)=2.02s    p(95)=2.11s   
        rating.................................: good=10   needs_improvement=10    poor=0
    first_input_delay..........................: p(75)=57.91ms  p(90)=57.91ms  p(95)=57.95ms 
        rating.................................: good=10    needs_improvement=0    poor=0
    interaction_to_next_paint..................: p(75)=80ms     p(90)=80ms     p(95)=80ms    
        rating.................................: good=10    needs_improvement=0    poor=0
    largest_content_paint......................: p(75)=415.54ms p(90)=415.54ms p(95)=416.67ms
        rating.................................: good=10    needs_improvement=0    poor=0
    time_to_first_byte.........................: p(75)=365.04ms p(90)=365.04ms p(95)=445.76ms
        rating.................................: good=10    needs_improvement=0    poor=0
```
